### ISSUE TITLE
Pop ups from Settings auto Close!

### ISSUE THREAD

**Issue by Om-Thorat** [lawrencehook/remove-youtube-suggestions#80]
### Attached a video i recorded to demonstrate the bug,
> It no longer occurs after i disable the RYS extension.

https://user-images.githubusercontent.com/76207818/223201148-77a4c32f-051e-4816-9397-2a0b8c813f68.mp4

### It seems like this might be relevant to issue #77 but i am not sure.

> On a side note RYS helps me focus a lot, Thanks for this amazing extension!

**Comment by lawrencehook** [comment]
@Om-Thorat Thanks for making the issue! I appreciate the video.

I _believe_ this bug is fixed as of the latest version (4.3.33)

**Comment by Om-Thorat** [comment]
Oh it is!
That was fast, Thanks.

**Comment by Om-Thorat** [comment]
It seems like it is happening again, I tried reinstalling just in case I wasn't on the latest version but the problem persists.

**Comment by lawrencehook** [comment]
It's happening to me too! I'll investigate

**Comment by lawrencehook** [comment]
Just released a new version (4.3.35) that should fix it -- hopefully for good this time

**Comment by Om-Thorat** [comment]
It's all good now,
Great hopefully we will meet on another thread next time!!
